name: Vault & Azure Login - Reusable

on:
  workflow_call:
    secrets:
      VAULT_TOKEN:
        required: true

jobs:
  login_azure_hvault:
    runs-on: self-hosted
    outputs:
      ARM_CLIENT_ID: ${{ steps.get-creds.outputs.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ steps.get-creds.outputs.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ steps.get-creds.outputs.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ steps.get-creds.outputs.ARM_TENANT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login en Vault
        shell: powershell
        env:
          VAULT_ADDR: http://127.0.0.1:8200
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
        run: |
          vault.exe login $env:VAULT_TOKEN
          vault.exe token lookup

      - name: Obtener credenciales DE Azure
        id: get-creds
        shell: powershell
        env:
          VAULT_ADDR: http://127.0.0.1:8200
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
        run: |

          $client_id = vault.exe kv get -field=ARM_CLIENT_ID secret/azure
          $client_secret = vault.exe kv get -field=ARM_CLIENT_SECRET secret/azure
          $subscription_id = vault.exe kv get -field=ARM_SUBSCRIPTION_ID secret/
          $tenantId = vault.exe kv get -field=ARM_TENANT_ID secret/azure

          echo "ARM_CLIENT_ID=$client_id" >> $env:GITHUB_OUTPUT
          echo "ARM_CLIENT_SECRET=$client_secret" >> $env:GITHUB_OUTPUT
          echo "ARM_SUBSCRIPTION_ID=$subscription_id" >> $env:GITHUB_OUTPUT
          echo "ARM_TENANT_ID=$tenantId" >> $env:GITHUB_OUTPUT

      - name: Login en Azure
        shell: powershell
        run: |
          az login --service-principal
            --username ${{ steps.get-creds.outputs.ARM_CLIENT_ID }} `
            --password ${{ steps.get-creds.outputs.ARM_CLIENT_SECRET }} `
            --tenant ${{ steps.get-creds.outputs.ARM_TENANT_ID }}
