name: credentials_azure

on:
  workflow_call:
    inputs:
      vault_addr:
        required: false
        type: string
        default: "http://127.0.0.1:8200"
      secret_path:
        required: false
        type: string
        default: "secret/azure"
      field:
        required: false
        type: string
        default: "DATABRICKS_TOKEN"
    secrets:
      VAULT_TOKEN:
        required: true
    outputs:
      databricks_token:            # <— SOLO este (lowercase)
        description: "Databricks PAT"
        value: ${{ jobs.get-token.outputs.databricks_token }}
      databricks_token_len:
        description: "Longitud del token (debug)"
        value: ${{ jobs.get-token.outputs.databricks_token_len }}

jobs:
  get-token:
    runs-on: self-hosted
    outputs:
      databricks_token: ${{ steps.get-creds.outputs.token }}
      databricks_token_len: ${{ steps.get-creds.outputs.token_len }}
    steps:
      - name: Login en Vault
        shell: bash
        env:
          VAULT_ADDR: ${{ inputs.vault_addr }}
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
          VAULT_SKIP_VERIFY: "true"
          PATH: ${{ env.PATH }}:/home/gha-runner/vault
        run: |
          set -Eeuo pipefail
          vault --version
          vault login "$VAULT_TOKEN" >/dev/null
          vault token lookup

      - name: Obtener token de Databricks
        id: get-creds
        shell: bash
        env:
          VAULT_ADDR: ${{ inputs.vault_addr }}
          VAULT_SKIP_VERIFY: "true"
          PATH: ${{ env.PATH }}:/home/gha-runner/vault
        run: |
          set -Eeuo pipefail
          dbToken="$(vault kv get -field='${{ inputs.field }}' '${{ inputs.secret_path }}')"
          if [ -z "$dbToken" ]; then echo "❌ Vault devolvió token vacío"; exit 1; fi
          echo "::add-mask::$dbToken"
          echo "token=$dbToken" >> "$GITHUB_OUTPUT"
          echo "token_len=${#dbToken}" >> "$GITHUB_OUTPUT"
