name: credentials-azure

on:
  workflow_call:
    inputs:
      vault_addr:
        type: string
        required: false
        default: "http://127.0.0.1:8200"
      skip_verify:
        type: boolean
        required: false
        default: true
    secrets:
      VAULT_TOKEN:
        required: true
    outputs:
      databricks_token:
        description: "Databricks PAT obtenido de Vault"
        value: ${{ jobs.creds.outputs.databricks_token }}

jobs:
  creds:
    runs-on: self-hosted
    outputs:
      databricks_token: ${{ steps.get.outputs.databricks_token }}
    steps:
      - name: Login en Vault
        shell: bash
        env:
          VAULT_ADDR: ${{ inputs.vault_addr }}
          VAULT_SKIP_VERIFY: ${{ inputs.skip_verify }}
          PATH: ${{ env.PATH }}:/home/gha-runner/vault
        run: |
          set -Eeuo pipefail
          vault --version
          vault login "${{ secrets.VAULT_TOKEN }}" >/dev/null
          vault token lookup

      - name: Obtener token de Databricks
        id: get
        shell: bash
        env:
          VAULT_ADDR: ${{ inputs.vault_addr }}
          VAULT_SKIP_VERIFY: ${{ inputs.skip_verify }}
          PATH: ${{ env.PATH }}:/home/gha-runner/vault
        run: |
          set -Eeuo pipefail
          dbToken=$(vault kv get -field=DATABRICKS_TOKEN secret/azure)
          echo "::add-mask::$dbToken"
          echo "databricks_token=$dbToken" >> "$GITHUB_OUTPUT"
