name: Vault & Azure Login - Reusable

on:
  workflow_call:

jobs:
  login_azure_hvault:
    runs-on: self-hosted
    outputs:
      ARM_CLIENT_ID: ${{ steps.get-creds.outputs.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ steps.get-creds.outputs.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ steps.get-creds.outputs.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ steps.get-creds.outputs.ARM_TENANT_ID }}

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Validar token en Vault
        shell: powershell
        env:
          VAULT_ADDR: http://127.0.0.1:8200
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
        run: |
          Write-Host "Validando conexión a Vault en $env:VAULT_ADDR"
          vault.exe token lookup

      - name: Obtener credenciales de Azure desde Vault
        id: get-creds
        shell: powershell
        env:
          VAULT_ADDR: http://127.0.0.1:8200
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
        run: |
          $clientId = vault.exe kv get -field=ARM_CLIENT_ID secret/azure
          $clientSecret = vault.exe kv get -field=ARM_CLIENT_SECRET secret/azure
          $subscriptionId = vault.exe kv get -field=ARM_SUBSCRIPTION_ID secret/azure
          $tenantId = vault.exe kv get -field=ARM_TENANT_ID secret/azure

          "ARM_CLIENT_ID=$clientId" >> $env:GITHUB_OUTPUT
          "ARM_CLIENT_SECRET=$clientSecret" >> $env:GITHUB_OUTPUT
          "ARM_SUBSCRIPTION_ID=$subscriptionId" >> $env:GITHUB_OUTPUT
          "ARM_TENANT_ID=$tenantId" >> $env:GITHUB_OUTPUT

      - name: Login en Azure
        shell: powershell
        run: |
          az login --service-principal `
            --username ${{ steps.get-creds.outputs.ARM_CLIENT_ID }} `
            --password ${{ steps.get-creds.outputs.ARM_CLIENT_SECRET }} `
            --tenant ${{ steps.get-creds.outputs.ARM_TENANT_ID }}
