name: deploy-databricks

on:
  workflow_call:
    inputs:
      databricks_host:
        type: string
        required: true
    secrets:
      DATABRICKS_TOKEN:
        required: true

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Validar conexión a Databricks
        shell: bash
        env:
          DATABRICKS_HOST: ${{ inputs.databricks_host }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          PATH: ${{ env.PATH }}:~/databricks-env/bin
        run: |
          set -Eeuo pipefail
          source ~/databricks-env/bin/activate || true
          databricks --version
          databricks workspace ls / >/dev/null
