name: Deploy ETL ADF

on:
  workflow_call:
    secrets:
      ACCOUNT_KEY:
        required: true

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4