name: Revisar/Crear Data Factory

on:
  workflow_call:
    inputs:
      location:
        required: false
        default: "eastus"
        type: string
    outputs:
      factory-status:
        value: ${{ jobs.check_create.outputs.factory-status }}

jobs:
  check_create:
    runs-on: self-hosted
    outputs:
      factory-status: ${{ steps.set-status.outputs.factory-status }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Verificar versión de Azure CLI
        shell: powershell
        run: az version